Django-master/website/music/urls.py
from django.conf.urls import url
from . import views


app_name = 'music';

urlpatterns = [
    url(r'^$', views.index, name='index'),  #$ means the homepasge for individual app
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail')
]

Django-master/website/music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genra = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - ' +self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

Django-master/website/music/views.py
from django.http import HttpResponse
from django.template import loader
from music.models import Album
from django.shortcuts import render
from django.http import Http404


def index(request):
    all_albums = Album.objects.all()
    template = loader.get_template('music/index.html')
    context = {
        'all_albums' : all_albums
    }

    # return HttpResponse(template.render(context, request))

    return render(request, 'music/index.html', context)


def detail(request, album_id):
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExits:
        raise Http404("Album does not exists")
    return render(request, 'music/details.html', {'album' : album})

Django-master/website/music/templates/music/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Album</title>
</head>
<body>
    <img src="{{ album.album_logo }}">

    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>

    <ul>
        {% for song in album.song_set.all %}
        <li> {{ song.song_title }} - {{ song.file_type }}</li>
        {% endfor %}
    </ul>
</body>
</html>

Django-master/website/music/templates/music/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Music</title>
</head>
<body>
{% if all_albums  %}
    <ul>
        {% for album in all_albums %}
        <li><a href="/music/{{ album.id }}">{{ album.album_title }}</a> </li>
        {% endfor %}
    </ul>
{% else  %}
    <h3>You have no album</h3>
{%  endif %}
</body>
</html>